name: fristproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # --- Existing Dependencies ---
  cupertino_icons: ^1.0.2
  percent_indicator: ^4.2.3
  fl_chart: ^0.68.0
  url_launcher: ^6.2.6

  # --- New Dependencies for Attendance System ---
  sqflite: ^2.3.0        # For local SQL database
  path: ^1.9.0           # For database paths
  mailer: ^6.0.0         # To send Emails directly
  telephony: ^0.2.0
  supabase_flutter: ^2.0.0
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.2.2
  flutter_background_service: ^5.0.0
  intl: ^0.19.0          # For formatting dates (e.g., 2025-01-20)
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

# ✅ Flutter launcher icon configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21  # optional

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icon/